Submit the form instead of clicking the Continue button
From the test failures in Concourse it looks like the button is
successfully being clicked(?) but nothing happens:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/usr/local/lib/python3.6/dist-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "behave/features/steps/general.py", line 40, in wrapper
    func(context, *args, **kwargs)
  File "behave/features/steps/general.py", line 150, in submit_the_form
    element.click()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.81)
  (Driver info: chromedriver=70.0.3538.16 (16ed95b41bb05e565b11fb66ac33c660b721f778),platform=Linux 5.4.0-1041-aws x86_64)
```

I have a suspicion that whilst the button is clickable Chrome misses it because
it moves. Chrome apparently doesn't handle this well[1]:

> ChromeDriver can't click a moving element
>
> This is not a supported feature of ChromeDriver. If the element eventually stops, wait for that to occur. If the element never stops moving, ChromeDriver does not guarantee the click will be successful.

We can try submitting the form rather than clicking the submit button.

[1] https://chromedriver.chromium.org/help/clicking-issues